Unite testing of dashboard module
onosproject/aether-enterprise-portal pull request #32
Opened 2022-02-28 05:09 UTC by kapilsolaki

2022-02-28 16:40 UTC, teone requested changes
I haven't commented on everything but I have a major concern with the implemented unit-tests as they are not checking on the operations they are invoking.

For example:
```
it('should run #ngOnInit()', async () => {
    component.form = component.formBuilder.group({
      email: component.email,
      password: component.password,
    });
    spyOn(component.formBuilder, 'group');
    component.ngOnInit();
    // expect(component.formBuilder.group).toHaveBeenCalled();
  });
```
is setting what `ngOnInit` would set.
A test that validates what `ngOnInit` is expected to do would look like:
```
  it('should run #ngOnInit()', async () => {
    spyOn(component.formBuilder, 'group');
    expect(component.formBuilder.group).toHaveBeenCalled();
    expect(component.form.get("email")).toEqual(component.email)
    expect(component.form.get("password")).toEqual(component.password)
  });
```
_NOTE that we are not calling `component.ngOnInit();` as that is automatically called by Angular itself_

2022-02-28 16:40 UTC, teone commented on src/app/Modules/auth/pages/login/login.component.ts
> +    // if (this.form.valid) {
we should remove the commented out code

2022-02-28 21:26 UTC, teone commented on src/app/Modules/auth/pages/login/login.component.spec.ts
> +  it('should run #getErrorMessage()', async () => {
another thing that I noticed is that all the tests are marked as `async`, while the code looks synchronous, what is the reason for that?

2022-03-07 15:50 UTC, SeanCondon commented
retest this please

2022-03-07 19:07 UTC, SeanCondon commented
@kapilsolaki - when I get past the License error I'm seeing intermittent Unit test failures with 
```
TypeError: Cannot read properties of undefined (reading '0')
      at SafeSubscriber._next (http://localhost:9876/_karma_webpack_/webpack:/src/app/Modules/dashboard/pages/slices/slices.component.ts:516:3)
```

2022-03-08 11:09 UTC, murali-vutti-zensark commented
retest this please

2022-03-08 18:42 UTC, teone reviewed
A lot of these tests are still not validating the code. Most don't even have an `expect` clause, the ones that have are only checking that some other method is called, but not that the code is behaving in the expected way.

2022-03-08 18:42 UTC, teone commented on src/app/Modules/auth/pages/login/login.component.spec.ts
> +    expect(component.email.hasError).toHaveBeenCalled();
Aside checking that the method is called you might want to check the return value of `getErrorMessage` to make sure it is returning the expected one.

It's not entirely clear to me what `component.email = component.email` is intended to achieve, you're assigning a variable the value it already has.

I believe a test like:
```
    spyOn(component.email, "hasError").and.callThrough();
    spyOn(component.password, "hasError").and.callThrough();
    
    component.email.setValue("foobar");
    component.password.setValue("testpassword");
    
    const res = component.getErrorMessage();
    
    expect(component.email.hasError).toHaveBeenCalledWith('required')
    expect(component.email.hasError).toHaveBeenCalledWith('email')
    expect(component.password.hasError).toHaveBeenCalledWith('required')
    expect(res).toEqual("Not a valid email");
```
will do a better job at validating that the code is working the way it's intended to.

With the current implementation I could the method under test to be:
```
// if (this.email.hasError('required') || this.password.hasError('required')) {
    //   return 'You must enter a value';
    // }
    //
    // return this.email.hasError('email') ? 'Not a valid email' : '';
    this.email.hasError(undefined)
    this.password.hasError(undefined)
    return 'The world is an amazing place'
```
and the test still pass

2022-03-08 18:42 UTC, teone commented on src/app/Modules/dashboard/pages/alerts/alerts.component.spec.ts
> +  it('should run #selectFilter()', () => {
not testing anything

2022-03-09 14:22 UTC, SeanCondon commented
retest this please

2022-03-09 14:45 UTC, SeanCondon approved these changes
Merging this so we can identify any new changes

2022-03-09 14:56 UTC, merged